packages:
  - 'apps/*'
  - 'packages/*'
publicHoistPattern:
  - '@electron-forge/*'
  - '@electron/*'
  - 'electron*'
minimumReleaseAge: 10080 # 7 days
minimumReleaseAgeStrict: true
blockExoticSubdeps: false # TODO: https://github.com/ArcaneWizards/open-source/issues/73
minimumReleaseAgeExclude:
  - '@arcanejs/diff@0.6.0'
  - '@arcanejs/protocol@0.9.0'
  - '@arcanejs/react-toolkit@0.16.0'
  - '@arcanejs/toolkit-frontend@0.12.0'
  - '@arcanejs/toolkit@9.0.0'
  - electron@35.7.5
  - tmp@0.2.4
  - tar@7.5.7
  - tar@7.5.3
  - tar@7.5.8
  - '@tootallnate/once@3.0.1'
  - tar@7.5.10
  - tar@7.5.11
  - tar@7.5.4
  - lodash@4.17.24
  - electron@38.8.6
  - electron@39.8.1
  - electron@39.8.5
  - '@xmldom/xmldom@0.8.12'
  - uuid@11.1.1
  - fast-uri@3.1.1
  - fast-uri@3.1.2
  - '@xmldom/xmldom@0.8.13'
  - ip-address@10.1.1
  - brace-expansion@5.0.6
  - ws@8.20.1
  - turbo@2.9.14
  - '@turbo/darwin-64@2.9.14'
  - '@turbo/darwin-arm64@2.9.14'
  - '@turbo/linux-64@2.9.14'
  - '@turbo/linux-arm64@2.9.14'
  - '@turbo/windows-64@2.9.14'
  - '@turbo/windows-arm64@2.9.14'
allowBuilds:
  '@arcanewizards/electron-media-service': true
  '@parcel/watcher': true
  electron: true
  electron-winstaller: true
  esbuild: false
  fs-xattr: true
  lzma-native: true
  macos-alias: true
  unrs-resolver: true
overrides:
  '@electron/rebuild': 4.0.4
  '@tootallnate/once@<3.0.1': ^3.0.1
  tar@<7.5.7: ^7.5.7
  tar@<7.5.8: ^7.5.8
  tar@<=7.5.10: ^7.5.11
  tar@<=7.5.2: ^7.5.3
  tar@<=7.5.3: ^7.5.4
  tar@<=7.5.9: ^7.5.10
  tmp@<=0.2.3: ^0.2.4
