name: Check, Build & Release
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  checks:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Use Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 22.20
      - name: Extract pnpm version and install
        run: |
          VERSION=$(cat package.json | grep '"packageManager": "pnpm@' | sed 's/.*"pnpm@\([^"]*\)".*/\1/')
          npm install -g pnpm@$VERSION
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm lint
      - run: pnpm format:check
      - run: pnpm test
  build-and-release-apps:
    strategy:
      matrix:
        app: [timecode-toolbox]
    name: build-and-release-${{ matrix.app }}
    uses: ./.github/workflows/build-and-release-app.yaml
    permissions:
      contents: write
    with:
      app: ${{ matrix.app }}
      macos_build_requested: ${{ contains(github.event.pull_request.labels.*.name, format('build-macos-{0}', matrix.app)) }}
      windows_build_requested: ${{ contains(github.event.pull_request.labels.*.name, format('build-windows-{0}', matrix.app)) }}
      notarize: ${{ github.ref_name == 'main' }}
    secrets: inherit
